version: "2"

services:
  voting-app:
    image: dockertrainingja/voting-app:20160712
    ports:
      - "80"
    networks:
      voteapp:
    labels:
     interlock.hostname: "vote"
     interlock.domain:   "example.org"
  result-app:
    image: dockertrainingja/result-app:20160712
    ports:
      - "80"
    networks:
      voteapp:
    labels:
     interlock.hostname: "result"
     interlock.domain:   "example.org"
  worker:
    image: dockertrainingja/worker:20160712
    networks:
      voteapp:
       aliases:
        - workers
  redis:
    image: redis:3.2
    ports:
      - "6379"
    networks:
      voteapp:
    container_name: redis

  db:
    image: postgres:9.4
    networks:
      voteapp:
    container_name: db

networks:
  voteapp:
